# Anleitung: https://wiki.hhu.de/display/BMFZIT/bcl2fastq2+Pipeline+-+Benutzeranleitung

bcl2fastq:
  barcode_mismatch: 1
  SampleSheet:
   /path/to/SampleSheet.csv
  OutputFolder:
   /path/to/OutputFolder
  options: ""
  threads: 12      
  bcl2fastq2_version: bcl2fastq/2.20.0

others:
  FastQC_version: /software/fastqc/0.11.4/fastqc
  fastQC_threads: 1
  SHA256_threads: 1

gocryptfs:
  gocryptfs_version: gocryptfs/1.7.1
  gocryptfs_active: False

cutadapt:
  cutadapt_version: cutadapt 
  cutadapt_active: False  
  cutadapt_threads: 1
  adapters: 
    - CTGTCTCTTATACACATCT
    - ACGGATCGATCGATCGATCGAT

  
  adapter_type: 
    - a
    - g
  other_params: ""

rseqc:
  rseqc_active: True
  gtf_file: "/path/to/gtf_file" 
  genomeDir: "/path/to/genomeDir"
  strandedness: False 
  STAR_threads: 12
  other_params: ""
  STAR_version: STAR/2.7.5a-git 
