# Anleitung: https://wiki.hhu.de/display/BMFZIT/bcl2fastq2+Pipeline+-+Benutzeranleitung

bcl2fastq:
  barcode_mismatch: 1
  SampleSheet:
   /path/to/csv
  OutputFolder:
   /path/to/outputfolder
  other_params: ""
  threads: 12

others:
  fastQC_threads: 1
  SHA256_threads: 1

gocryptfs:
  gocryptfs_version: gocryptfs/1.7.1
  gocryptfs_active: False

cutadapt:
  cutadapt_active: True  
  cutadapt_threads: 1
  adapters: 
    - CTGTCTCTTATACACATCT
    - ACGGATCGATCGATCGATCGAT

  
  adapter_type: 
    - a
    - g
  other_params: ""

rseqc:
  rseqc_active: True
  gtf_file: "/path/to/gtf" 
  genomeDir: "/path/to/genomeDir"
  strandedness: False 
  STAR_threads: 12
  other_params: ""

umi_tools:
  umi_tools_active: True
  pattern: "NNNNNNNNNN" # 6nt umi + tata = 10nt UMI
  extended_name: "umiextr"
  umi_tools_dedup_bam: True
  threads: 12
  stranded: 1 # featurecounts parameter -s 