# Anleitung: https://wiki.hhu.de/display/BMFZIT/bcl2fastq2+Pipeline+-+Benutzeranleitung

bcl2fastq:
  barcode_mismatch: 1
  SampleSheet:
   /path/to/csv
  OutputFolder:
   /path/to/outputfolder
  other_params: ""
  threads: 12
  options: ""
  bcl_convert_path: "/gpfs/project/projects/bmfz_gtl/software/software_tests/bcl2fastq2_update/bcl-convert"
  bcl2fastq2_version: "2.20.0.422"


  

others:
  fastQC_threads: 1
  SHA256_threads: 1

gocryptfs:
  gocryptfs_version: gocryptfs/1.7.1
  gocryptfs_active: False

cutadapt:
  cutadapt_active: True  
  cutadapt_threads: 1
  adapters: 
    - CTGTCTCTTATACACATCT
    - ACGGATCGATCGATCGATCGAT

  
  adapter_type: 
    - a
    - g
  other_params: ""

rseqc:
  rseqc_active: True
  gtf_file: "/path/to/gtf" 
  genomeDir: "/path/to/genomeDir"
  strandedness: False 
  STAR_threads: 12
  other_params: ""

umi_tools:
  umi_tools_active: True
  pattern: '"(?P<umi_1>.{6})(?P<discard_1>TATA).+"'' # 6nt umi + tata = 10nt UMI
  extended_name: "umiextr"
  umi_tools_dedup_bam: True
  threads: 12
  stranded: 1 # featurecounts parameter -s 

kraken2:
  kraken2_active: True
  kraken2_database: "/gpfs/project/databases/Kraken2-2022-09-28/kraken_db_plus"
  kraken2_threads: 2


transfer:
  transfer_active: True
  transfer_to: "134.99.204.8:/mnt/data/pipelines/"
  transfer_as: "daniel@"


 # add instructions for ssh-keygen and ssh-copy-id daniel@134.99.204.8
 # add settings for receiving folder 2>&1